-- Find total customers by countries
select
	country,
	count(distinct customer_key) as Total_customers
from gold.dim_customers
group by country
order by Total_customers desc

-- Find total customers by gender
select
	gender,
	count(distinct customer_key) as Total_customers
from gold.dim_customers
group by gender

-- Find total products by category
select
	category,
	count (distinct product_key) as Total_product_count
from gold.dim_products
group by category
order by category

-- What is the average costs in each category?
select
	category,
	avg(unit_cost) avg_category_cost
from gold.dim_products
group by category
order by avg_category_cost desc

-- What is the total revenue generated for each category?
select
	p.category,
	sum(s.sales_amount_usd) as Total_revenue
from gold.dim_products as p
left join gold.fact_sales as s  --- i use left join in order to know if there is any category which does not drive for revenue yet
on p.product_key = s.product_key
group by p.category
order by Total_revenue desc

-- What is the total revenue generated by each customer?
select
	c.customer_key,
	c.customer_name,
	sum(sales_amount_usd) as Total_revenue
from gold.dim_customers as c
left join gold.fact_sales as s --- i use left join in order to know if there is any customer which does not drive for revenue yet
on c.customer_key = s.customer_key
group by c.customer_key, c.customer_name
order by Total_revenue desc

-- What is the distribution of sold items across countries?

select
	c.country,
	sum(s.quantity) as Total_unit_sold
from gold.dim_customers as c
left join gold.fact_sales as s
on c.customer_key = s.customer_key
group by c.country
order by Total_unit_sold desc